[project]
name = "langgraph-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fangyang", email = "fangyang1@xiaoyouzi.com" }
]
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.4.3",
    "langchain-anthropic>=1.7.5",
    "langchain-openai>=1.6.7",
    "langgraph>=1.2.14",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.4",
]

[project.scripts]
langgraph-py = "langgraph_py:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
]
