import { readFileSync } from 'fs';
import { join } from 'path';
import { computeOnlineRisk, RiskDraw } from './online-risk-ranking.model';
import { OnlineRiskRankingService } from './online-risk-ranking.service';

// Golden data exported from the Python training run, not generated by the TS model.
const fixture = JSON.parse(
  readFileSync(join(__dirname, 'fixtures/online-risk-2026.json'), 'utf8'),
) as {
  numbers: number[][];
  predictions: number[];
  next: number;
};
const draws: RiskDraw[] = fixture.numbers.map((numbers, i) => ({
  year: 2026,
  No: i + 1,
  numbers,
}));
const records = draws.map((r) => ({
  year: r.year,
  No: r.No,
  ...Object.fromEntries(r.numbers.map((n, i) => [`n${i + 1}`, n])),
}));

describe('OnlineRiskRanking', () => {
  it('matches every Python prediction, 90/100 audit, and the next experimental candidate', () => {
    const result = computeOnlineRisk(draws);
    expect(result.rows.map((r) => r.predictedNumber)).toEqual(
      fixture.predictions,
    );
    expect(result.rows.filter((r) => r.No >= 151 && r.success)).toHaveLength(
      90,
    );
    expect(result.prediction?.number).toBe(fixture.next);
    expect(result.prediction?.ranking).toHaveLength(49);
    expect(new Set(result.prediction?.ranking.map((r) => r.number)).size).toBe(
      49,
    );
  });

  it('never changes earlier predictions when later draws are appended', () => {
    const prefix = computeOnlineRisk(draws.slice(0, 200));
    const full = computeOnlineRisk(draws);
    expect(full.rows.filter((r) => r.No <= 200)).toEqual(prefix.rows);
    expect(full.rows.find((r) => r.No === 201)?.predictedNumber).toBe(
      prefix.prediction?.number,
    );
    expect(full.weightHistory.filter((r) => r.afterNo <= 200)).toEqual(
      prefix.weightHistory,
    );
  });

  it('filters other years, sorts input, and caches only an unchanged source', async () => {
    const mock = {
      findAll: jest
        .fn()
        .mockResolvedValue([
          { ...records[0], year: 2025 },
          ...records.slice().reverse(),
        ]),
    };
    const service = new OnlineRiskRankingService(mock as any);
    const result = await service.getPrediction();
    expect(mock.findAll).toHaveBeenCalledWith(2026);
    expect(result).toMatchObject({
      status: 'ready',
      historyCount: 250,
      target: { year: 2026, No: 251 },
      prediction: { number: 5 },
      stages: { audit: { count: 100, successCount: 90, targetPassed: false } },
    });
    expect(await service.getPrediction()).toBe(result);
    mock.findAll.mockResolvedValue([
      ...records,
      { year: 2026, No: 251, n1: 1, n2: 2, n3: 3, n4: 4, n5: 5, n6: 6, n7: 7 },
    ]);
    const updated = await service.getPrediction();
    expect(updated).not.toBe(result);
    expect(updated).toMatchObject({
      target: { year: 2026, No: 252 },
      stages: { after250: { count: 1, failureCount: 1 } },
    });
  });

  it.each([
    ['missing period', records.filter((r) => r.No !== 80)],
    ['missing first period', records.slice(1)],
    ['duplicate period', [...records, records[0]]],
    ['duplicate ball', [{ ...records[0], n1: 8, n2: 8 }, ...records.slice(1)]],
    ['fractional ball', [{ ...records[0], n1: 1.5 }, ...records.slice(1)]],
  ])('does not publish a prediction for %s', async (_, input) => {
    const service = new OnlineRiskRankingService({
      findAll: jest.fn().mockResolvedValue(input),
    } as any);
    const result = await service.getPrediction();
    expect(result.status).toBe('invalid-history');
    expect(result).not.toHaveProperty('prediction');
  });

  it('handles empty data and the exact warmup boundary without fake statistics', async () => {
    const mock = { findAll: jest.fn().mockResolvedValue([]) };
    const service = new OnlineRiskRankingService(mock as any);
    expect(await service.getPrediction()).toMatchObject({
      status: 'insufficient-history',
      historyCount: 0,
    });
    mock.findAll.mockResolvedValue(records.slice(0, 40));
    expect(await service.getPrediction()).toMatchObject({
      status: 'ready',
      target: { No: 41 },
      rolling: expect.arrayContaining([
        {
          window: 10,
          count: 0,
          successCount: 0,
          failureCount: 0,
          successRate: null,
          specialCodeMissCount: 0,
          specialCodeMissRate: null,
        },
      ]),
    });
  });
});
