import { useEffect, useState } from 'react';

const pct = (value) => typeof value === 'number' ? `${(value * 100).toFixed(1)}%` : '--';
function Metric({ label, data }) { return <article className="ap-metric"><span>{label}</span><strong>{pct(data?.successRate)}</strong><small>{data?.successCount || 0}/{data?.count || 0} 成功</small></article>; }

export default function AnchorPhase14Kill() {
  const [data, setData] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => {
    const controller = new AbortController();
    fetch('/api/kill/anchor-phase-14', { cache: 'no-store', signal: controller.signal })
      .then(async (response) => { const json = await response.json(); if (!response.ok) throw new Error(json.message || `HTTP ${response.status}`); return json; })
      .then(setData).catch((reason) => reason.name !== 'AbortError' && setError(reason.message || '加载失败'));
    return () => controller.abort();
  }, []);
  const prediction = data?.prediction;
  const bt = data?.backtests || {};
  return <main className="ap-page"><style>{`
    .ap-page{min-height:100vh;box-sizing:border-box;padding:72px 18px 48px;color:#fff7ed;background:radial-gradient(circle at 85% 0,rgba(244,114,182,.17),transparent 34%),#181118;font-family:Inter,system-ui,sans-serif}.ap-shell{width:min(1160px,100%);margin:0 auto}.ap-kicker{margin:0 0 10px;color:#f9a8d4;font-size:12px;font-weight:900;letter-spacing:.14em;text-transform:uppercase}.ap-title{margin:0;font-size:clamp(32px,5vw,56px);line-height:1}.ap-subtitle{max-width:790px;margin:14px 0 26px;color:#c2adb9;line-height:1.7}.ap-panel{border:1px solid rgba(249,168,212,.17);border-radius:20px;background:rgba(40,25,37,.87);box-shadow:0 24px 72px rgba(0,0,0,.28)}.ap-message{padding:24px;color:#d8c3ce}.ap-error{color:#fda4af}
    .ap-hero{display:grid;grid-template-columns:minmax(0,1.08fr) minmax(380px,.92fr);gap:16px}.ap-current{padding:28px}.ap-equation{display:flex;align-items:center;gap:13px;flex-wrap:wrap;margin-top:18px}.ap-token{padding:15px 18px;border-radius:15px;background:rgba(244,114,182,.11);border:1px solid rgba(249,168,212,.18)}.ap-token span,.ap-token strong{display:block}.ap-token span{color:#bda4b1;font-size:11px}.ap-token strong{margin-top:5px;font-size:22px}.ap-arrow{color:#f9a8d4;font-size:22px;font-weight:900}.ap-ball{display:grid;place-items:center;width:96px;height:96px;border-radius:50%;color:#fff1f2;background:#db2777;font-size:38px;font-weight:950;box-shadow:0 16px 38px rgba(219,39,119,.3)}.ap-copy{margin:18px 0 0;color:#d8c8d0;font-size:13px;line-height:1.65}.ap-tags{display:flex;flex-wrap:wrap;gap:7px;margin-top:14px}.ap-tag{padding:6px 10px;border-radius:999px;color:#fbcfe8;background:rgba(244,114,182,.1);font-size:11px;font-weight:800}
    .ap-metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.ap-metric{padding:18px;border:1px solid rgba(244,114,182,.2);border-radius:16px;background:rgba(40,25,37,.68)}.ap-metric span,.ap-metric small{display:block;color:#aa919f}.ap-metric strong{display:block;margin:7px 0 4px;font-size:30px}.ap-long{grid-column:1/-1}.ap-lower{display:grid;grid-template-columns:.75fr 1.25fr;gap:16px;margin-top:16px}.ap-card{padding:22px}.ap-card h3{margin:0 0 14px;font-size:17px}.ap-values{display:grid;gap:10px}.ap-values div{padding:13px;border-radius:12px;background:rgba(255,255,255,.035)}.ap-values span{display:block;color:#ad95a2;font-size:11px}.ap-values strong{display:block;margin-top:5px;font-size:17px}.ap-table-wrap{overflow-x:auto}.ap-table{width:100%;min-width:800px;border-collapse:collapse;font-size:13px}.ap-table th,.ap-table td{padding:10px 8px;border-bottom:1px solid rgba(255,255,255,.07);text-align:left}.ap-table th{color:#a08795;font-size:11px}.ap-ok{color:#f9a8d4;font-weight:850}.ap-bad{color:#fb7185;font-weight:850}@media(max-width:900px){.ap-hero,.ap-lower{grid-template-columns:1fr}.ap-long{grid-column:auto}}@media(max-width:540px){.ap-metrics{grid-template-columns:1fr 1fr}.ap-ball{width:78px;height:78px}.ap-token{padding:11px}}
  `}</style><div className="ap-shell">
    <p className="ap-kicker">Anchor plus period phase</p><h1 className="ap-title">14期锚点＋期号相位</h1><p className="ap-subtitle">固定读取14期前第4位 x 与上一期开奖期号 q，计算 −3x + 2q − 19，再循环回绕至1～49。</p>
    {error && <div className="ap-panel ap-message ap-error">加载失败：{error}</div>}{!error && !data && <div className="ap-panel ap-message">正在计算500期滚动回测…</div>}{data?.status === 'insufficient-history' && <div className="ap-panel ap-message">{data.message}</div>}
    {prediction && <><div className="ap-hero"><section className="ap-panel ap-current"><p className="ap-kicker">当前推荐单杀</p><div className="ap-equation"><div className="ap-token"><span>14期前第4位 x</span><strong>{prediction.anchorDisplay}</strong></div><div className="ap-token"><span>上一期期号 q</span><strong>{prediction.phaseNo}</strong></div><span className="ap-arrow">→</span><div className="ap-ball">{prediction.display}</div></div><p className="ap-copy">{prediction.reason}</p><div className="ap-tags"><span className="ap-tag">{prediction.formula}</span><span className="ap-tag">{prediction.wrapFormula}</span><span className="ap-tag">锚点 {prediction.source.year}-{String(prediction.source.No).padStart(3,'0')}</span></div></section>
    <div className="ap-metrics"><Metric label="近20期" data={bt.backtest20}/><Metric label="近50期" data={bt.backtest50}/><Metric label="近100期" data={bt.backtest100}/><Metric label="近200期" data={bt.backtest200}/><div className="ap-long"><Metric label="近500期长期观察" data={bt.backtest500}/></div></div></div>
    <div className="ap-lower"><section className="ap-panel ap-card"><h3>本期计算</h3><div className="ap-values"><div><span>x：14期前第4位</span><strong>{prediction.anchorNumber}</strong></div><div><span>q：上一期期号</span><strong>{prediction.phaseNo}</strong></div><div><span>原始公式</span><strong>−3 × {prediction.anchorNumber} + 2 × {prediction.phaseNo} − 19 = {prediction.rawValue}</strong></div><div><span>循环回绕</span><strong>{prediction.wrapFormula}</strong></div></div></section>
    <section className="ap-panel ap-card ap-table-wrap"><h3>近20期逐期核验</h3><table className="ap-table"><thead><tr><th>开奖期</th><th>锚点期</th><th>x</th><th>q</th><th>公式</th><th>结果</th></tr></thead><tbody>{bt.backtest20.rows.map(row=><tr key={`${row.year}-${row.No}`}><td>{row.year}-{String(row.No).padStart(3,'0')}</td><td>{row.anchorYear}-{String(row.anchorNo).padStart(3,'0')}</td><td>{row.anchorDisplay}</td><td>{row.phaseNo}</td><td>{row.formula}</td><td className={row.success?'ap-ok':'ap-bad'}>{row.success?'成功':'失败'}</td></tr>)}</tbody></table></section></div></>}
  </div></main>;
}
