import { useEffect, useState } from 'react';

const pct = (value) => typeof value === 'number' ? `${(value * 100).toFixed(1)}%` : '--';
function Metric({ label, data }) { return <article className="tgd-metric"><span>{label}</span><strong>{pct(data?.successRate)}</strong><small>{data?.successCount || 0}/{data?.count || 0} 成功</small></article>; }

export default function TailGatedDualKill() {
  const [data, setData] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => {
    const controller = new AbortController();
    fetch('/api/kill/tail-gated-dual', { cache: 'no-store', signal: controller.signal })
      .then(async (response) => { const json = await response.json(); if (!response.ok) throw new Error(json.message || `HTTP ${response.status}`); return json; })
      .then(setData).catch((reason) => reason.name !== 'AbortError' && setError(reason.message || '加载失败'));
    return () => controller.abort();
  }, []);
  const p = data?.prediction;
  const bt = data?.backtests || {};
  return <main className="tgd-page"><style>{`
    .tgd-page{min-height:100vh;box-sizing:border-box;padding:72px 18px 48px;color:#f8fafc;background:radial-gradient(circle at 50% 0,rgba(45,212,191,.15),transparent 36%),#0d1515;font-family:Inter,system-ui,sans-serif}.tgd-shell{width:min(1180px,100%);margin:0 auto}.tgd-kicker{margin:0 0 10px;color:#5eead4;font-size:12px;font-weight:900;letter-spacing:.14em;text-transform:uppercase}.tgd-title{margin:0;font-size:clamp(32px,5vw,56px);line-height:1}.tgd-subtitle{max-width:820px;margin:14px 0 26px;color:#a6b7b5;line-height:1.7}.tgd-panel{border:1px solid rgba(94,234,212,.17);border-radius:20px;background:rgba(19,38,37,.87);box-shadow:0 24px 72px rgba(0,0,0,.28)}.tgd-message{padding:24px;color:#bfd0ce}.tgd-error{color:#fda4af}
    .tgd-hero{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(390px,.9fr);gap:16px}.tgd-current{padding:28px}.tgd-gate{display:flex;align-items:center;gap:14px;flex-wrap:wrap;margin-top:18px}.tgd-tail{display:grid;place-items:center;width:82px;height:82px;border-radius:18px;color:#042f2e;background:#5eead4;font-size:34px;font-weight:950}.tgd-route{padding:14px 17px;border-radius:15px;background:rgba(45,212,191,.1);border:1px solid rgba(94,234,212,.19)}.tgd-route span,.tgd-route strong{display:block}.tgd-route span{color:#8ca9a5;font-size:11px}.tgd-route strong{margin-top:5px;font-size:18px}.tgd-arrow{color:#5eead4;font-size:22px;font-weight:900}.tgd-ball{display:grid;place-items:center;width:96px;height:96px;border-radius:50%;color:#ecfeff;background:#0f766e;font-size:38px;font-weight:950;box-shadow:0 16px 38px rgba(15,118,110,.32)}.tgd-copy{margin:18px 0 0;color:#c8d7d5;font-size:13px;line-height:1.65}.tgd-tags{display:flex;flex-wrap:wrap;gap:7px;margin-top:14px}.tgd-tag{padding:6px 10px;border-radius:999px;color:#99f6e4;background:rgba(45,212,191,.09);font-size:11px;font-weight:800}
    .tgd-metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.tgd-metric{padding:18px;border:1px solid rgba(45,212,191,.2);border-radius:16px;background:rgba(19,38,37,.67)}.tgd-metric span,.tgd-metric small{display:block;color:#8ba4a1}.tgd-metric strong{display:block;margin:7px 0 4px;font-size:30px}.tgd-long{grid-column:1/-1}.tgd-branches{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:16px}.tgd-branch{padding:22px}.tgd-branch.active{border-color:rgba(94,234,212,.5);background:rgba(15,118,110,.13)}.tgd-branch h3{margin:0 0 8px}.tgd-branch p{margin:0;color:#a8bbb8;font-size:13px;line-height:1.6}.tgd-branch b{display:block;margin-top:14px;color:#99f6e4}.tgd-card{padding:22px;margin-top:16px}.tgd-card h3{margin:0 0 14px}.tgd-table-wrap{overflow-x:auto}.tgd-table{width:100%;min-width:880px;border-collapse:collapse;font-size:13px}.tgd-table th,.tgd-table td{padding:10px 8px;border-bottom:1px solid rgba(255,255,255,.07);text-align:left}.tgd-table th{color:#819b98;font-size:11px}.tgd-ok{color:#5eead4;font-weight:850}.tgd-bad{color:#fb7185;font-weight:850}@media(max-width:920px){.tgd-hero{grid-template-columns:1fr}.tgd-long{grid-column:auto}}@media(max-width:620px){.tgd-branches{grid-template-columns:1fr}.tgd-metrics{grid-template-columns:1fr 1fr}.tgd-tail{width:68px;height:68px}.tgd-ball{width:78px;height:78px}}
  `}</style><div className="tgd-shell">
    <p className="tgd-kicker">Period-tail gated formula</p><h1 className="tgd-title">期号尾门控双公式</h1><p className="tgd-subtitle">先用上一期期号尾数选择固定分支，再执行对应公式。尾数集合与两个分支全部冻结，不根据近期结果切换。</p>
    {error && <div className="tgd-panel tgd-message tgd-error">加载失败：{error}</div>}{!error && !data && <div className="tgd-panel tgd-message">正在计算500期门控回测…</div>}{data?.status === 'insufficient-history' && <div className="tgd-panel tgd-message">{data.message}</div>}
    {p && <><div className="tgd-hero"><section className="tgd-panel tgd-current"><p className="tgd-kicker">当前推荐单杀</p><div className="tgd-gate"><div className="tgd-tail">{p.periodTail}</div><div className="tgd-route"><span>上一期期号 {p.phaseNo} · 尾数命中</span><strong>{p.branchLabel}</strong></div><span className="tgd-arrow">→</span><div className="tgd-ball">{p.display}</div></div><p className="tgd-copy">{p.reason}</p><div className="tgd-tags"><span className="tgd-tag">{p.formula}</span><span className="tgd-tag">锚点 {p.source.year}-{String(p.source.No).padStart(3,'0')}</span><span className="tgd-tag">锚点第{p.anchorPosition}位 {p.anchorNumber}</span></div></section>
      <div className="tgd-metrics"><Metric label="近20期" data={bt.backtest20}/><Metric label="近50期" data={bt.backtest50}/><Metric label="近100期" data={bt.backtest100}/><Metric label="近200期" data={bt.backtest200}/><div className="tgd-long"><Metric label="近500期长期观察" data={bt.backtest500}/></div></div></div>
      <div className="tgd-branches"><section className={`tgd-panel tgd-branch ${p.branch==='quad'?'active':''}`}><h3>尾数 0 / 2 / 3 / 5 / 6 / 7</h3><p>读取上一期第7位 x。</p><b>4x − 2</b></section><section className={`tgd-panel tgd-branch ${p.branch==='phase'?'active':''}`}><h3>尾数 1 / 4 / 8 / 9</h3><p>读取14期前第4位 x 与上一期期号 q。</p><b>−3x + 2q − 19</b></section></div>
      <section className="tgd-panel tgd-card tgd-table-wrap"><h3>近20期逐期门控核验</h3><table className="tgd-table"><thead><tr><th>开奖期</th><th>期号尾</th><th>命中分支</th><th>锚点期</th><th>公式</th><th>结果</th></tr></thead><tbody>{bt.backtest20.rows.map(row=><tr key={`${row.year}-${row.No}`}><td>{row.year}-{String(row.No).padStart(3,'0')}</td><td>{row.periodTail}</td><td>{row.branchLabel}</td><td>{row.anchorYear}-{String(row.anchorNo).padStart(3,'0')}</td><td>{row.formula}</td><td className={row.success?'tgd-ok':'tgd-bad'}>{row.success?'成功':'失败'}</td></tr>)}</tbody></table></section></>}
  </div></main>;
}
